apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oauth2-proxy-namespace.yaml
  - sealed-oauth2-proxy-azure-secret.yaml
  - oauth2-proxy-helmrepository.yaml
  - oauth2-proxy-helmrelease.yaml
