apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.19
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    installCRDs: true
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true
      annotations: {}
      conversion:
        enabled: true
    leaderElect: false
    processClusterExternalSecret: true
    processClusterStore: true
    processPushSecret: true
    createOperator: true
    replicaCount: 1
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    service:
      type: ClusterIP
      port: 80
    metrics:
      enabled: true
      port: 9000
      serviceMonitor:
        enabled: false
    webhook:
      port: 9443
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    rbac:
      create: true
      servicebindings:
        create: true
    serviceAccount:
      create: true
      automount: true
      annotations: {}
      extraLabels: {}
      name: "external-secret"
    logLevel: info
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
