apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 168h
    promtail:
      enabled: true
      config:
        existingConfigMap: promtail-config
    service:
      type: NodePort
      nodePort: 31001 # You can specify a NodePort or let Kubernetes choose one
