apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    deploymentMode: SimpleScalable
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: "filesystem"
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            index:
              prefix: loki_index_
              period: 24h
            object_store: filesystem
            schema: v13
      config: |
        table_manager:
          retention_deletes_enabled: true
          retention_period: 168h
    singleBinary:
      replicas: 0
    read:
      replicas: 1
    write:
      replicas: 1
    backend:
      replicas: 1
    promtail:
      enabled: true
      config:
        existingConfigMap: promtail-config
    service:
      type: NodePort
      nodePort: 31001
