apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    deploymentMode: SimpleScalable
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: s3
        s3:
          endpoint: http://minio.minio.svc.cluster.local:9000
          bucketnames: loki
          access_key_id: loki
          secret_access_key: supersecret
          s3forcepathstyle: true
          insecure: true
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            index:
              prefix: loki_index_
              period: 24h
            object_store: s3
            schema: v13
      config: |
        table_manager:
          retention_deletes_enabled: true
          retention_period: 168h
    read:
      replicas: 1
    write:
      replicas: 1
    backend:
      replicas: 1
    promtail:
      enabled: true
      config:
        existingConfigMap: promtail-config
    service:
      type: NodePort
      nodePort: 31001
    minio:
      enabled: true
