apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluxcd
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flux
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http
      interval: 30s
