apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana/
  - loki/
  - prometheus/
  - fluxcd-servicemonitor.yaml
  - crossplane-servicemonitor.yaml
  - kubelet-servicemonitor.yaml
