apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: capacitor
  path: "./clusters/docker-desktop/capacitor" # Replace with the actual path to your Kustomization
  prune: true
  timeout: 5m
