apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-deploy
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/docker-desktop/cert-deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
