apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-config
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/docker-desktop/crossplane"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # dependsOn:
  #   - name: xrds
