apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: komoplane
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/docker-desktop/komoplane"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
