---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-resources
  namespace: flux-system
spec:
  interval: 1m
  path: "./crossplane-resources/managed-resources"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
