apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mdp-helm-template
  namespace: flux-system
spec:
  interval: 1m
  path: "./crossplane-resources/mdp-poc"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
