apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: xrds
  namespace: flux-system
spec:
  interval: 1m
  path: "./crossplane-resources/xrds"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
