namespace: test-landing-zone

providerConfigRef: kishore-azure-config

resourceGroup:
  name: mdp-poc-resource-group
  externalName: mdp-poc
  location: West Europe

## Commenting for further troubleshoot ##
kubernetesClusters:
  - name: mesh-cluster-test1
    providerConfigRefName: kishore-azure-config
    location: West Europe
    resourceGroupName: mdp-poc
    kubernetesVersion: 1.28.9
    privateClusterEnabled: true
    dnsPrefix: mesh-aks-dns
    automaticChannelUpgrade: stable
    httpApplicationRoutingEnabled: true
    runCommandEnabled: true
    identity:
      - identityIds:
          - "/subscriptions/1947901f-c34b-4ff0-98e7-0f0acf01b5a7/resourcegroups/mdp-poc/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-identity"
        type: UserAssigned
    networkProfile:
      - dnsServiceIp: "10.0.0.10"
        networkMode: ""
        networkPlugin: "azure"
        networkPolicy: "calico"
        serviceCidrs:
          - "10.0.0.0/16"
        podCidrs:
          - "10.1.128.0/17"
    defaultNodePool:
      - name: default
        nodeCount: 1
        maxCount: 5
        minCount: 1
        maxPods: 250
        vmSize: Standard_DS2_v2
        enableAutoScaling: true
        temporaryNameForRotation: "temp-nodepool"
        type: "VirtualMachineScaleSets"
        upgradeSettings:
          - maxSurge: "10%"
        vnetSubnetId: "/subscriptions/1947901f-c34b-4ff0-98e7-0f0acf01b5a7/resourceGroups/mdp-poc/providers/Microsoft.Network/virtualNetworks/k8s-vnet/subnets/k8s-subnet"
        zones:
          - "1"
          - "2"
          - "3"
    linuxProfile:
      - adminUsername: "ansible"
        sshKey:
          - keyData: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1BAAfPuD/vE7t+5z+dz7YQepiU+7NYqtHtpept1k+LsIhtx5RiNGTBeo7pLa87ODNCbz5cvM7DS67YahgdX3hF0wibroERNpmdL8J1Uokn3r/kXfK3qU/RzYP71doR5kpxwq2z7qBgbMvjC2WoD45rvaDTPf+0eyoObcTHt4gOBQb1Ic9y377IPd9qxYhw7vJwqFjNF46qKChEVKRl2+yA79B3JiXsMdOnGk1qtBWz2gVBrhgxYS3985Ry75eOinLCjibmzQYnqoqvxw2MHU16RILNYYnOW7Q++PyfM4Yxoa6Vq3gZxDMkTwKTBrcLvOmukkFwL5/m/U75xb53ZDiZ0lxWEXiq6FnoK91M1dUL6V5upMTCJJOKfZInwK465UwhZOX7GC8wr1/hyXP2w4p8Vxs2k4vWKsPziM48yVJgEQra+wHV5Hg5T/nIPL0sCLWf6kNjxRFXyGl36kQgeoTy3A92JJ7vUkgctRCKFNnZ23mNbWgYJBZhlaq084iKHE="
  # - name: mesh-cluster-test2
  #   providerConfigRefName: kishore-azure-config
  #   location: West Europe
  #   resourceGroupName: mdp-poc
  #   kubernetesVersion: 1.28.9
  #   privateClusterEnabled: true
  #   dnsPrefix: mesh-aks-dnss
  #   automaticChannelUpgrade: stable
  #   httpApplicationRoutingEnabled: true
  #   runCommandEnabled: true
  #   identity:
  #     - identityIds:
  #         - "/subscriptions/1947901f-c34b-4ff0-98e7-0f0acf01b5a7/resourcegroups/mdp-poc/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-identity"
  #       type: UserAssigned
  #   networkProfile:
  #     - dnsServiceIp: "10.0.0.10"
  #       networkMode: ""
  #       networkPlugin: "azure"
  #       networkPolicy: "calico"
  #       serviceCidrs:
  #         - "10.0.0.0/16"
  #       podCidrs:
  #         - "10.1.128.0/17"
  #   defaultNodePool:
  #     - name: default
  #       nodeCount: 1
  #       maxCount: 5
  #       minCount: 1
  #       maxPods: 250
  #       vmSize: Standard_DS2_v2
  #       enableAutoScaling: true
  #       temporaryNameForRotation: "temp-nodepool"
  #       type: "VirtualMachineScaleSets"
  #       upgradeSettings:
  #         - maxSurge: "10%"
  #       vnetSubnetId: "/subscriptions/1947901f-c34b-4ff0-98e7-0f0acf01b5a7/resourceGroups/mdp-poc/providers/Microsoft.Network/virtualNetworks/k8s-vnet/subnets/k8s-subnet"
  #       zones:
  #         - "1"
  #         - "2"
  #         - "3"
