---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds:
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane-system
