---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCp64YQENXOlIUCczB6G8iBu2r7gTyRIXQ6QZlqggPk9epVgPcYzs6jvCy5we0jkkLFQy9bDIPaT2UP7M80IBUp1sDwnw7qEhczGGNISKmyCms9QYfjS7S/XSw0V4ZvROUkeX7HBI4x57J7PDwDUOZW6HILIdAPmKNBq3aExLHFjylwjY+cz5rXw0SxzLTjy2e8rTt2Twxb3yfXniPJOU5kkEbrCaQKxJm9/vOgZiR2Ja3SdmpzuvH0WlB5eIB3KnMBlPvS8HEMtyvuinyXyuOSNC6gJicyS4eOq/Ed1jO07Vu5ixCtOW9eFNMEHuGxjvWhWD72Ybbyy0dwKZS2g12Z5GrYwtV5scrAJPkSqUr7IxdsAiS2UuGOPAV5K1mpXzvh5MkJ3EU56+oJiwS2IjZkdXPYHkAXEv41UBPDELROvV6YMpQlON+XcSnzCB1DHuFwjcfcWeZpHehbVSIcbUlbOQqLBR2eRz5ik1EyP0miV2cmNphBzFUJsM96/TgXFurLWNzf5tK6Dyb3i3nFiNabR0ORham4U+yET8HeUikAF3YnRWil+iFlZYrdy26xOZV+CoPpIrgiLjonS/17axu4yrmHvpBPiwVgkmTyxcuj04mNhVTBtD1K1YgogAViYiBfyW98qygXRO3ZzrWIzGRdmWzfGMV2euuf0wt0vT3P9bjAwFSdHsEOtBTPXe5M4xJBuFNWDNYAYPUCGiVMnnxFx1cLtHN+sB1X4uEEIJ/C770bx1PQQVbroYXTxKfgFWcv/Fch52GOzRScIqDBWt4mcPIobVp9WHEr7fYL3W0L0DKyDyHTeoaWC1R2iGUZv8O4AvZVJtP6ic0XZqk12+RVlMxsIaoUac3pRICahHHbdrlZBvqQ0C/mvhNazfnJU0AN6Eiy0I6N5450hApNYCpLrnjfKaOQGpYFI6GMOMiUF1Hc40T5ZJIxE8b24PjGAHadrQyHqpe8NtmpSNc7/WjJTTuqqHXrUHP2uBcjjkOzMj6CzcrnhkD0IhiWJT7///jcrOLo3FVtApsgtufTvLG0iy7nCHVmAgVFF+h2i0F9qgUlW77QlfmH5glmImCHPeeBqNyc4mPqy8wwsCVozKayocct7KzbtvDmTWoz2yDFmQ1mH/A5PVSqxFbbA9i7lAjjJIO7NcJpT3ZTL7jMXaTZ7keyVevaDARXvXwDVc3hU3LglYdTko2LM+BN7JtRPG+Zahh1mpcGXoIKC+SDwUc9qOv/DnOBTS2aeiYcVLbItNEJzBp1qmenqWPiBHA6jtrxrRBOv/tzcHKkEEP6cDL+gMg9/DWUmQNOcpyhIhjuY8+qbZZOO/hsKPBoZd4OSNSS3/XyHosGEryYmqAaCkSxRAyOESRTj8oil5XfRtVGRUzIPxWUTdAVoTkElGaKx7lUG5GHE9byQ+WjdOZgYcHKnsmZUQj9nkF80vYSMprgk/u8rpa0b276f+G1jkcuumNzXL1d/hiZaMaG/1LhL7f+WQP7a7pQpKuvxVf4772vALGbHQirj/ZbVB1zYyIFfT52
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane-system
