apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 60.0.2
  values:
    prometheusRuleSelectorNilUsesHelmValues: false
    additionalPrometheusRules:
      - name: custom-rules
        groups:
          - name: my_alerts
            rules:
              - alert: HighErrorRate
                annotations:
                  description: More than 5% of requests are failing with 500 errors
                  summary: High request error rate
                expr: rate(http_requests_total{status="500"}[5m]) > 0.05
                for: 10m
                labels:
                  severity: page
    alertmanager:
      enabled: true
    coreDns:
      enabled: false
    coreDnsServiceMonitor:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeEtcdServiceMonitor:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeControllerManagerServiceMonitor:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeSchedulerServiceMonitor:
      enabled: false
    kubeProxy:
      enabled: false
    kubeProxyServiceMonitor:
      enabled: false
    nodeExporter:
      hostRootFsMount: false
    prometheus:
      prometheusSpec:
        scrapeInterval: "30s"
        evaluationInterval: "30s"
        ruleSelector:
          matchLabels:
            role: alert-rules
        ruleNamespaceSelector: {}
    defaultRules:
      rules:
        alertmanager: true
        etcd: true
        general: true
        kubeApiserver: true
        kubePrometheusNodeAlerting: true
        kubePrometheusNodeRecording: true
        kubeScheduler: true
        kubeStateMetrics: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        node: true
        prometheus: true
        prometheusOperator: true
