apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 60.0.2
  values:
    additionalPrometheusRulesMap:
      custom-rules:
        groups:
          - name: my_alerts
            rules:
              - alert: HighErrorRate
                expr: rate(http_requests_total{status="500"}[5m]) > 0.05
                for: 10m
                labels:
                  severity: page
                annotations:
                  summary: High request error rate
                  description: More than 5% of the requests are failing with 500 errors in the last 10 minutes.
    alertmanager:
      enabled: true
    coreDns:
      enabled: false
    coreDnsServiceMonitor:
      enabled: false
    defaultRules:
      rules:
        alertmanager: true
        etcd: true
        general: true
        kubeApiserver: true
        kubePrometheusNodeAlerting: true
        kubePrometheusNodeRecording: true
        kubeScheduler: true
        kubeStateMetrics: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        node: true
        prometheus: true
        prometheusOperator: true
    kubeControllerManager:
      enabled: false
    kubeControllerManagerServiceMonitor:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeEtcdServiceMonitor:
      enabled: false
    kubeProxy:
      enabled: false
    kubeProxyServiceMonitor:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeSchedulerServiceMonitor:
      enabled: false
    nodeExporter:
      extraArgs:
        - --path.procfs=/proc
        - --path.sysfs=/sys
        - --web.listen-address=0.0.0.0:9100
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
      volumeMounts:
        - mountPath: /host/proc
          name: proc
        - mountPath: /host/sys
          name: sys
        - mountPath: /host/root
          name: root
          mountPropagation: None
      hostRootFsMount: false
    prometheus:
      prometheusSpec:
        scrapeInterval: "30s"
        evaluationInterval: "30s"
        ruleSelector:
          matchLabels:
            role: alert-rules
        ruleNamespaceSelector: {}
    prometheusRuleSelectorNilUsesHelmValues: false
