apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 60.0.2
  values:
    prometheusRuleSelectorNilUsesHelmValues: false
    defaultRules:
      rules:
        alertmanager: true
        etcd: true
        general: true
        kubeApiserver: true
        kubePrometheusNodeAlerting: true
        kubePrometheusNodeRecording: true
        kubeScheduler: true
        kubeStateMetrics: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        node: true
        prometheus: true
        prometheusOperator: true
    prometheus:
      prometheusSpec:
        ruleSelector:
          matchLabels:
            role: alert-rules
        ruleNamespaceSelector: {}
    additionalPrometheusRulesMap: |
      prometheus:
        - alert: HighErrorRate
          annotations:
            description: More than 5% of the requests are failing with 500 errors in the last 10 minutes.
            summary: High request error rate
          expr: rate(http_requests_total{status="500"}[5m]) > 0.05
          for: 10m
          labels:
            severity: page
    alertmanager:
      enabled: true
    nodeExporter:
      hostRootFsMount: false
    kubeEtcd:
      enabled: false
    kubeEtcdServiceMonitor:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeControllerManagerServiceMonitor:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeSchedulerServiceMonitor:
      enabled: false
    kubeProxy:
      enabled: false
    kubeProxyServiceMonitor:
      enabled: false
    coreDns:
      enabled: false
    coreDnsServiceMonitor:
      enabled: false
    kubeDns:
      enabled: false
    kubeDnsServiceMonitor:
      enabled: false
