apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - ../fluxcd-servicemonitor.yaml
  - ../crossplane-servicemonitor.yaml
  - ../kubelet-servicemonitor.yaml
