apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capacitor-tls
  namespace: flux-system
spec:
  secretName: capacitor-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: capacitor.example.com
  dnsNames:
    - capacitor.example.com

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: komoplane-tls
  namespace: komoplane
spec:
  secretName: komoplane-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: komoplane.example.com
  dnsNames:
    - komoplane.example.com

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: flux-system
spec:
  isCA: true
  commonName: ca.local
  secretName: ca-cert
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capacitor-tls
  namespace: flux-system
spec:
  secretName: capacitor-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: capacitor.local
  dnsNames:
    - capacitor.local

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: komoplane-tls
  namespace: komoplane
spec:
  secretName: komoplane-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: komoplane.local
  dnsNames:
    - komoplane.local
