apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kishore-behera/fluxcd-crossplane-idp
  ref:
    branch: main
  ignore: []
