apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/gimlet-io/capacitor
  ref:
    tag: v0.3.3
